### ISSUE TITLE
Support additional arguments for kombu.Connection

### ISSUE THREAD

**Issue by dekmetzi** [ansible/asgi_amqp#9]
This only passes off the url, which prevents using this (and awx) with rabbit that requires tls client certificates (amongst other options). It should permit configuring additional options.

https://github.com/ansible/asgi_amqp/blob/master/asgi_amqp/core.py#L76
https://docs.celeryproject.org/projects/kombu/en/4.6.7/reference/kombu.connection.html

**Comment by dekmetzi** [comment]
I should note that other kwargs can be set as url params, though as ssl is a dict that doesn't work (without specific support in kombu)

**Comment by wwitzel3** [comment]
@miketzian is this an issue you might have time to make a PR for?

**Comment by dekmetzi** [comment]
Since awx no longer depends on this, I don't need it anymore. (revisiting this work after a busy year)

thanks!
